all:
	gcc coordsread.c -o  coordsread
	gcc coordswrite.c -o coordswrite

remakeall:
	rm coordsread
	rm coordswrite
	gcc coordsread.c -o coordsread
	gcc coordswrite.c -o coordswrite

shell:
	gcc shell.c -o shell

clean:
	rm shell
	rm coordsread
	rm coordswrite
	rm outfile
