all:
	gcc p1.c -o p1
	gcc p2.c -o p2
	gcc p3.c -o p3
	gcc p4.c -o p4
	gcc p5.c -o p5
	gcc p6.c -o p6
	gcc p7.c -o p7
	gcc p8.c -o p8
	gcc p9.c -o p9

p1: 
	gcc p1.c -o p1

p2:
	gcc p2.c -o p2

p3: 
	gcc p3.c -o p3

p4:
	gcc p4.c -o p4

p5:
	gcc p5.c -o p5

p6:
	gcc p6.c -o p6

p7:
	gcc p7.c -o p7

p8:
	gcc p8.c -o p8

p9:
	gcc p9.c -o p9

clean:
	rm p1
	rm p2
	rm p3
	rm p4
	rm p5
	rm p6
	rm p7
	rm p8
	rm p9
	rm p2.txt	
